name: changelog

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check_changelog:
    runs-on: ubuntu-20.04
    env:
      NO_CHANGELOG: '[X] No CHANGELOG update needed'
    steps:
    - name: Get changed files
      id: files
      uses: jitterbit/get-changed-files@v1
    - name: check changelog updated
      env:
        PR_BODY: ${{ github.event.pull_request.body }}
        FILES: ${{ steps.files.outputs.modified }}
      run: |
        echo $FILES | grep -qF 'CHANGELOG.md' || echo $PR_BODY | grep -qF "$NO_CHANGELOG"
    - name: Reject pull request if no CHANGELOG update
      if: ${{ failure() }}
      uses: andrewmusgrave/automatic-pull-request-review@0.0.5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        event: REQUEST_CHANGES
        body: "Please add bug fixes, new features, breaking changes and anything else you think it is worthwhile mentioning to the `master (unreleased)` section of CHANGELOG.md. If no CHANGELOG update is needed add the following to the PR description: `${{ env.CHANGELOG }}`"
    - name: Dismiss previous review if CHANGELOG update
      uses: andrewmusgrave/automatic-pull-request-review@0.0.5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        event: DISMISS

